- name: find_and_read_tacac
  hosts: all
  tasks:

   - name: Find /etc tac_plus.conf
     find:
       paths: /etc
       recurse: yes
       file_type: file
       patterns: 'tac_plus.conf'
     register: find_result

   - name: print find_result
     debug: var=find_result.files[0].path

   - name: Set global variable mon_id
     set_fact: tac_plus_conf="{{hostvars[inventory_hostname].find_result.files[0].path}}"

   - name: Include vars of {{ tac_plus_conf }}into the 'tac_plus' variable (2.2).
     include_vars: {{item}}
     with_items: "{{tac_plus_conf}}"